### ISSUE TITLE
Unhandled LangDetectException

### ISSUE THREAD

**Issue by evothreat** [cve-search/git-vuln-finder#17]
Some commit-messages do not contain any valid words (from known languages), which leads to Exception from langdetect-package. This exception isn't handled, causing the program to stop. It would be nice, if the finder could simply catch and set language to None, when such kind of Exception is raised.

For example:

A try to parse https://github.com/jenkinsci/script-security-plugin will always fail, because it's repository has a commit named like this:

> https //github.com/jenkinsci/script-security-plugin/pull/348#discussion_r634333189

**Comment by adulau** [comment]
Good catch. I'll have a look into it. Thank you.

**Comment by adulau** [comment]
Thank you. It's now fixed in the latest version v1.4.
